config/routes.rb
Foxbasealpha::Application.routes.draw do
  
  

  root :to => 'Session#new'

  get "session/new"

  post "session/create"

  get "session/destroy"

  resources :users do
    resources :microposts
  end

  resources :alphas do
  end

  get '/alphas/:alpha_id/user/new' => "Alphas#new_alpha_user", :as => "new_alpha_user"

  post '/alphas/:alpha_id/user/create' => 'Alphas#new_alpha_user_create'

  

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
	@user = User.find_by_email(params[:email])
	    if @user && @user.authenticate(params[:password])
	      session[:user_id] = @user.id
	      if @user.site_admin
	      	  flash[:message] = "Welcome back admin"
		      redirect_to users_url
		  else
		 	  flash[:message] = "Fox Base Alpha Connect Initiated"
		   	  redirect_to user_url(session[:user_id])
		   end
	    else
	      flash[:message] = "Invalid login e-mail or password"
	      redirect_to session_new_url
	    end

  end

  def destroy
  	session[:user_id] = nil #KILL THIS GODDAMN THING
    flash[:message] = "Fox Base Alpha Connect Terminated"
    redirect_to session_new_url
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.haml
.landing_page_container

	%h1.landing_page_title FOX BASE ALPHA
	
	.landing_page_form

		=form_tag session_create_url
	
		.landing_page_labels
			%p= label_tag :email, "Email:"
			%p= label_tag :password, "Password:"	
		
		.landing_page_fields
			%p= text_field_tag :email 	
			%p= password_field_tag :password
		
		.initiate_connect= submit_tag "Initiate Connect"
	
	=link_to "Not a user? Sign-up", new_user_url