config/routes.rb
Foxbasealpha::Application.routes.draw do
  
  

  root :to => 'Session#new'

  get "session/new"

  post "session/create"

  get "session/destroy"

  resources :users do
    resources :microposts
  end

  resources :alphas do
  end

  get '/alphas/:alpha_id/user/new' => "Alphas#new_alpha_user", :as => "new_alpha_user"

  post '/alphas/:alpha_id/user/create' => 'Alphas#new_alpha_user_create'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :handle, :site_admin


  validates :email, :uniqueness => true, :on => :create
  validates :handle, :uniqueness => true, :on => :create
  validates :handle, :uniqueness => true, :on => :update
  validates :email, :uniqueness => true, :on => :update
  has_many :microposts
  has_many :whitelists

  after_destroy :remove_all_whitelists_attached_to_user_at_destroy
  after_destroy :remove_all_microposts_attached_to_user_at_destroy

  has_secure_password

  def remove_all_whitelists_attached_to_user_at_destroy
    Whitelist.where(user_id: self.id).destroy_all
  end

  def remove_all_microposts_attached_to_user_at_destroy
  	Micropost.where(user_id: self.id).destroy_all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :ensure_correct_user, only: [:show, :edit, :update]
  before_filter :ensure_site_admin, only: [:index, :destroy]
  before_filter :ensure_logged_in, except: [:new, :create]

   def ensure_logged_in
    if !session[:user_id]
      flash[:message] = "You are not logged in, please log in."
      redirect_to session_new_url
      return
    end
  end

  def ensure_correct_user
    user = User.find_by_id(session[:user_id])
    unless user.site_admin
      if session[:user_id] != params[:id].to_i
        flash[:message] = "You are not authorized to see/edit/delete any other User's information."
        redirect_to user_url(session[:user_id])
      end
    end
  end

  def ensure_site_admin
    user = User.find_by_id(session[:user_id])
      unless user.site_admin
        flash[:message] = "User list only available to admins"
        redirect_to user_url(session[:user_id])        
    end
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(session[:user_id])
    @user_microposts = Micropost.where(user_id: session[:user_id])
    @alphas_for_microposts = []

    @user_microposts.each do |user_micropost|
      @alphas_for_microposts << Alpha.find_by_id(user_micropost.alpha_id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.haml
.new_user_form

  =form_for(@user) do |f|

    .field
      =f.label :name
      %br
      =f.text_field :name
    .field
      =f.label :email
      %br 
      =f.text_field :email 
      %br
    .field
      =f.label :handle
      %br
      =f.text_field :handle 
    .field
      =f.label :password
      %br
      =f.password_field :password
    .field
      =f.label :password_confirmation
      %br
      =f.password_field :password_confirmation
    .action
      =f.submit 

app/views/users/edit.haml
.edit_user_container	
	%h1 Editing user

	=render('form')

	=link_to 'Show', @user

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Microposts', user_path(user.id) %>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to 'Alphas', alphas_path %>

app/views/users/new.haml
.new_user_container

	%h1 New user

	= render 'form'

	= link_to 'or Terminate', root_url

app/views/users/show.haml
%p#notice= notice

%p
	<b>Name:</b>
	=@user.name
%p
	<b>Email:</b>
	=@user.email

<b>Your last 100 Microposts:</b>

%ol
	-@user_microposts.each do |user_micropost|
		%li
			-if user_micropost.anonymous
				%p 
					You anonymously said... 
					= user_micropost.content
			-else
				%p
					You said
					= user_micropost.content

		%p
			on
			= link_to user_micropost.alpha.name, alpha_url(user_micropost.alpha.id)
			at
			= user_micropost.created_at.to_datetime

=link_to 'Edit User Information |', edit_user_path(@user) 
= link_to ' Back', users_path