config/routes.rb
Foxbasealpha::Application.routes.draw do
  
  

  root :to => 'Session#new'

  get "session/new"

  post "session/create"

  get "session/destroy"

  resources :users do
    resources :microposts
  end

  resources :alphas do
  end

  get '/alphas/:alpha_id/user/new' => "Alphas#new_alpha_user", :as => "new_alpha_user"

  post '/alphas/:alpha_id/user/create' => 'Alphas#new_alpha_user_create'

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id, :lat, :alpha_id, :anonymous, :micropost_lat, :micropost_lng

  belongs_to :user
  belongs_to :alpha

  validates_presence_of :content
  validates_presence_of :alpha_id

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json

  before_filter :on_the_whitelist, only: [:create]
  before_filter :ensure_logged_in

   def ensure_logged_in
    unless session[:user_id]
      flash[:message] = "You are not logged in, please log in."
      redirect_to session_new_url
      return
    end
  end

  def on_the_whitelist
    if Alpha.find_by_id(params["micropost"]["alpha_id"]).isprivate 
      if Whitelist.where(user_id: session[:user_id], alpha_id: params["micropost"]["alpha_id"]).empty?
      flash[:message] = "This is a private Alpha and you are not on it's authoerized posting list."
      redirect_to new_user_micropost_url(session[:user_id])
      end
    end
  end

  def index
    @user = User.find_by_id(session[:user_id])
    @user_microposts = Micropost.where(user_id: session[:user_id]).limit(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])
    @user = User.find_by_id(@micropost.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new
    @user_id = session[:user_id]
    public_alphas = Alpha.where(:isprivate => false)

    whitelist = Whitelist.where(user_id: session[:user_id]).to_a
    private_alphas = []
    whitelist.each do |whitelist_entry|
      if Alpha.find_by_id(whitelist_entry.alpha_id).isprivate == true
        private_alphas << Alpha.find_by_id(whitelist_entry.alpha_id)
      end
    end

    @alphas = public_alphas + private_alphas 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
    @user_id = @micropost.user_id
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])
    @micropost.user_id = session[:user_id]

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to user_microposts_path(@micropost.user.id), notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to user_micropost_path(@micropost.user_id, @micropost.id), notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to user_microposts_path(@micropost.user_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.haml
= form_for @micropost do |f| 
  -if @micropost.errors.any? 
    %div#error_explanation
      %h2 = pluralize(@micropost.errors.count, "error") prohibited this micropost from being saved:
      %ul
        - @micropost.errors.full_messages.each do |msg| 
          %li = msg

  .field
    = f.label :content
    %br
    = f.text_field :content 

  .field
    = f.label :user_id
    %br
    = f.text_field :user_id, value: @user_id 

  .field
    = f.label :alpha_id
    %br
    = f.text_field :alpha_id 

  .actions
    = f.submit 
    

app/views/microposts/edit.haml
%h1 Editing micropost

= form_for @micropost, :url => user_micropost_path(@user_id, @micropost.id), :method => :put do |f|
  - if @micropost.errors.any?
    %div#error_explanation
      %h2 = pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:
      %ul
        -@micropost.errors.full_messages.each do |msg|
          %li = msg

  .field
    = f.label :content
    %br
    = f.text_field :content

  .field
    = f.label :anonymous, "Post anonymously"
    = f.check_box :anonymous, value: true
  .actions
    = f.submit
    
= link_to 'Show', user_micropost_path(@user_id, @micropost.id)
= link_to 'Back', user_microposts_path(@user_id)

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Alpha</th>
    <th>Anonymous</th>
    <th></th>
    <th></th>
  </tr>

<% @user_microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user.name %></td>
    <% if micropost.alpha %>
        <td><%= link_to micropost.alpha.name, alpha_path(micropost.alpha.id) %></td>
    <% else %>
        <td>No alpha</td>
    <% end %>
    <% if micropost.anonymous %>
        <td>Anonymous</td>
    <%else%>
        <td>Not Anonymous</td>
    <%end%>
    <td><%= link_to 'Show', user_micropost_url(micropost.user_id, micropost.id) %> |</td> 
    <td><%= link_to 'Edit', edit_user_micropost_path(micropost.user_id, micropost.id) %> |</td>
    <td><%= link_to 'Destroy', user_micropost_url(micropost.user_id, micropost.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_user_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%#= render 'form' %>
<p id="test"></p>

<%= form_for @micropost, :url => user_microposts_path(@user_id), :method => :post do |f| %>
    <% if @micropost.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
        <ul>
          <% @micropost.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%#= f.label :user_id %><br />
    <%#= f.text_field :user_id, value: @user_id %>
  </div>
  <div class="field">
    <%= f.collection_select :alpha_id, @alphas, :id, :name %>
    <%= f.label :alpha_id, "Upload to Alpha" %><br />
    <%#= f.text_field :alpha_id %>
  </div>
  <div class="field">
    <%= f.label :anonymous, "Post anonymously" %>
    <%= f.check_box :anonymous, value: true %>
  </div>

  <div id="field">
    <%= f.label :micropost_lat, "Micropost's latitude" %>
    <%= f.text_field :micropost_lat%>
  </div>

  <div id="field">
    <%= f.label :micropost_lng, "Micropost's longitude" %>
    <%= f.text_field :micropost_lng%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  <div id="location">

  </div>
<%= link_to 'Back', user_microposts_path(@user_id) %>

<p id="messagelocation"></p>

<article>
  <p id="accuracy"></p>
</article>

<!-- <script type="text/javascript" src="alpha_location.js.coffee".></script>
 -->

app/views/microposts/show.haml
%p#notice 
	=notice

%p
	%b Content:
	= @micropost.content 

%p
	%b User:
	= link_to @user.handle, user_url(@user.id) 

= link_to 'Edit', edit_user_micropost_path(@micropost.user_id, @micropost.id) 
= link_to 'Back', user_microposts_path(@micropost.user_id) 