config/routes.rb
Foxbasealpha::Application.routes.draw do
  
  

  root :to => 'Session#new'

  get "session/new"

  post "session/create"

  get "session/destroy"

  resources :users do
    resources :microposts
  end

  resources :alphas do
  end

  get '/alphas/:alpha_id/user/new' => "Alphas#new_alpha_user", :as => "new_alpha_user"

  post '/alphas/:alpha_id/user/create' => 'Alphas#new_alpha_user_create'

  

end

app/models/alpha.rb
class Alpha < ActiveRecord::Base
  attr_accessible :name, :admin_id, :isprivate, :alpha_lat, :alpha_lng, :radius

  has_many :microposts
  has_many :whitelists
  has_many :users, :through => :whitelists

  before_create :no_duplicate_entries
  after_create :add_creator_to_whitelist
  after_destroy :remove_all_microposts_attached_to_alpha_at_destroy
  after_destroy :remove_all_whitelist_entries_at_destroy

  validates_presence_of :name

  scope :private_alphas, where("isprivate == ?", true)

  def add_creator_to_whitelist
  	Whitelist.create(user_id: self.admin_id, alpha_id: self.id)
  end

  def no_duplicate_entries

  end

  def remove_all_whitelist_entries_at_destroy
    Whitelist.where(alpha_id: self.id).destroy_all
  end

  def remove_all_microposts_attached_to_alpha_at_destroy
    Micropost.where(alpha_id: self.id).destroy_all
  end

  def points
    points = []
    microposts = Micropost.where(alpha_id: self.id)

    microposts.each do |micropost|
      point = []
      point[0] = micropost.micropost_lat
      point[1] = micropost.micropost_lng
      point[2] = micropost.content
      point[3] = User.find_by_id(micropost.user_id).name
      point[4] = User.find_by_id(micropost.user_id).handle
      points << point
    end

    return points
  end

  def nearby_microposts
    microposts = Micropost.where(alpha_id: self.id)
  end

end

app/controllers/alphas_controller.rb
class AlphasController < ApplicationController
# GET /alphas
# GET /alphas.json

# before_filter :ensure_logged_in, except: [:new, :create]
# before_filter :ensure_correct_user_type
before_filter :ensure_admin, only: [:edit, :update, :destroy ]
before_filter :ensure_admin_for_whitelisting, only: [:new_alpha_user, :new_alpha_user_create]
before_filter :ensure_logged_in

def ensure_logged_in
  if !session[:user_id]
    flash[:message] = "You are not logged in, please log in."
    redirect_to 
    return
  end
end

def ensure_admin
  if session[:user_id] != Alpha.find_by_id(params[:id]).admin_id
    flash[:message] = "Only an Alpha's creator can alter an Alpha's properties"
    redirect_to alphas_url
  end
end

def ensure_admin_for_whitelisting
  if session[:user_id] != Alpha.find_by_id(params[:alpha_id]).admin_id
    flash[:message] = "Only an Alpha's creator can alter an Alpha's properties"
    redirect_to alpha_url(params[:alpha_id])
  end
end


def index
  @public_alphas = Alpha.where(:isprivate => false)

  whitelist = Whitelist.where(user_id: session[:user_id]).to_a
  @private_alphas = []
  whitelist.each do |whitelist_entry|
    if Alpha.find_by_id(whitelist_entry.alpha_id).isprivate
      @private_alphas << Alpha.find_by_id(whitelist_entry.alpha_id)
    end
  end

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @alphas }
  end
end

# GET /alphas/1
# GET /alphas/1.json
def show
  @alpha = Alpha.find(params[:id])
  @admin = User.find_by_id(@alpha.admin_id)
  @microposts = @alpha.microposts
  @points = @alpha.points
  @js_microposts= []
  whitelist = Whitelist.where(alpha_id: @alpha.id)

  @microposts.each do |micropost_object|
    micropost_object_json = micropost_object.to_json
    @js_microposts << micropost_object_json
  end

  @users = []
  whitelist.each do |list_entry|
    @users << User.find_by_id(list_entry.user_id)
  end

  @json_response = []
  @json_response << @microposts

  respond_to do |format|
    format.html # show.html.erb
    format.json { render json: @json_response }
  end
end

# GET /alphas/new
# GET /alphas/new.json
def new
  @alpha = Alpha.new

  respond_to do |format|
    format.html # new.html.erb
    format.json { render json: @alpha }
  end
end

# GET /alphas/1/edit
def edit
  @alpha = Alpha.find(params[:id])
end

# POST /alphas
# POST /alphas.json
def create
  user = User.find_by_id(session[:user_id])
  @alpha = Alpha.new(params[:alpha])
  @alpha.admin_id = User.find_by_email(user.email).id

  respond_to do |format|
    if @alpha.save
      format.html { redirect_to @alpha, notice: 'Alpha was successfully created.' }
      format.json { render json: @alpha, status: :created, location: @alpha }
    else
      format.html { render action: "new" }
      format.json { render json: @alpha.errors, status: :unprocessable_entity }
    end
  end
end

# PUT /alphas/1
# PUT /alphas/1.json
def update
  @alpha = Alpha.find(params[:id])

  respond_to do |format|
    if @alpha.update_attributes(params[:alpha])
      format.html { redirect_to @alpha, notice: 'Alpha was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: "edit" }
      format.json { render json: @alpha.errors, status: :unprocessable_entity }
    end
  end
end

# DELETE /alphas/1
# DELETE /alphas/1.json
def destroy
  @alpha = Alpha.find(params[:id])
  @alpha.destroy

  respond_to do |format|
    format.html { redirect_to alphas_url }
    format.json { head :no_content }
  end
end

def new_alpha_user
  @whitelist = Whitelist.new
  @alpha_id = params[:alpha_id]
  @users = User.all
  @user = User.find_by_id(session[:user_id])
end

def new_alpha_user_create
  Whitelist.create(user_id: params[:whitelist][:user_id], alpha_id: params[:whitelist][:alpha_id])

  respond_to do |format|
    format.html { redirect_to alpha_url(params[:alpha_id])}
  end
end


end

app/helpers/alphas_helper.rb
module AlphasHelper
end

app/views/alphas/_form.haml
= form_for(@alpha) do |f|
  - if @alpha.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@alpha.errors.count, "error") 
        prohibited this alpha from being saved:
      %ul
        - @alpha.errors.full_messages.each do |msg| 
          %li = msg 

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label(:isprivate, "Make Alpha Private") 
    = f.radio_button(:isprivate, true) 
    = f.label(:isprivate, "Make Alpha Public") 
    = f.radio_button(:isprivate, false) 

  .field
    = f.label(:alpha_lat, "Alpha's source Latitude") 
    = f.text_field :alpha_lat 
    = f.label(:alpha_lng, "Alpha's source Longitude") 
    = f.text_field :alpha_lng 
    = f.label(:radius, "Alpha's size (in meters)") 
    = f.text_field :radius, value: 200 

  .actions
    = f.submit 

%script(type="text/javascript" src="alpha_location.js")

app/views/alphas/edit.haml
%h1 Editing alpha

= render 'form'

%article
  %p#accuracy

= link_to 'Show', @alpha
= link_to 'Back', alphas_path

app/views/alphas/index.haml
.block_container.clearfix
  %h1 
    Alphas /
    %a= link_to 'New Alpha', new_alpha_path 

  -@public_alphas.each do |alpha| 
    .block 
      %p
        =alpha.name 
        %br
        Public
        %br 
        =link_to 'Show', alpha 
        -if alpha.admin_id == session[:user_id]  
          /
          =link_to 'Edit', edit_alpha_path(alpha) 
          /
          =link_to 'Destroy', alpha, method: :delete, data: { confirm: 'Are you sure?' } 

  -@private_alphas.each do |alpha| 
    .block
      %p
        =alpha.name 
        %br
        Private
        %br 
        =link_to 'Show', alpha 
        -if alpha.admin_id == session[:user_id] 
          %td 
            =link_to 'Edit', edit_alpha_path(alpha) 
          %td 
            =link_to 'Destroy', alpha, method: :delete, data: { confirm: 'Are you sure?' } 
            -if alpha.admin_id == session[:user_id] 
              \-- you are admin

app/views/alphas/new.haml
%h1 New alpha

= render 'form'

%article
  %p#accuracy

= link_to 'Back', alphas_path

app/views/alphas/new_alpha_user.haml
%h1 New alpha user

= form_for @whitelist, :url => "/alphas/#{@alpha_id}/user/create", :method => :post do |f| 

  .field
    = f.hidden_field :alpha_id, value: @alpha_id
  .field
    =f.label :user_id, "Add a user"
    %br
    =f.collection_select :user_id, @users, :id, :name 
  
  .actions
    = f.submit "Add user to Whitelist"

= link_to 'Back', alphas_path 

app/views/alphas/show.haml
%p#notice= notice

%h1.alpha_title
  =@alpha.name

.alpha_title_block.clearfix

  .one_by_two_block

    .title_sub_block
      %p
        Address here!

    .title_sub_block
      %p
        = @alpha.radius  
        m access radius 

  .one_by_two_block#no_margin

    .title_sub_block
      %p  
        = @alpha.alpha_lat 
        %b Lat.

    .title_sub_block
      %p
        = @alpha.alpha_lng
        %b Lng.

  .three_by_one_block

    .title_sub_block
      %p
        %b Admin
        %br
        = @admin.handle

    .title_sub_block
      %p
        -if @alpha.isprivate 
          %b Private
        -else
        %b Public 
        %br
        Any can post

    .title_sub_block
      %p
        %b= @alpha.microposts.count
        %b posts 
        %br
        by
        %br
        %b= @alpha.users.count
        -if @alpha.users.count <= 1
          %b user
        -else
          %b users

/ .title_sub_block
/   -if @alpha.isprivate
/     %p
/       %b Whitelisted Users:
/       -if @users.count >= 1
/         %ul
/           -@users.each do |user_entry|
/             %li
/               =user_entry.name 
/               -if user_entry.id == @alpha.admin_id 
/                 is admin
/       -else
/         None
        

.alpha_microposts
  %p 
    %div.post.clearfix
      <b>Alpha Microposts:</b>
      %ul.micropost
        -@microposts.each do |micropost_object| 
          %li.each_post
            -if micropost_object.anonymous 
              %p Anonymous says... 
            -else 
              %p
                =link_to micropost_object.user.handle, user_microposts_path(micropost_object.user_id)
                says...
            %p= micropost_object.content 
            %p
              Coordinates: 
              =micropost_object.micropost_lat
              lat / 
              =micropost_object.micropost_lng
              lng 
    
            

%div#map.clearfix
  %b Micropost Locations:
  %br

%div#data_a

  -if @alpha.isprivate && @alpha.admin_id == session[:user_id]
    =link_to 'Add User', new_alpha_user_path(@alpha.id)
  
  -if @alpha.admin_id == session[:user_id] 
    =link_to 'Edit Alpha', edit_alpha_path(@alpha)
  
  =link_to 'Back to Alphas', alphas_path 

%article
  %p
    Finding your location: <span id="status">checking...</span>

%script(type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false")

%script(type="text/javascript" src="myloc.js")